
package br.com.maplink2.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddressFinderSoap", targetNamespace = "http://webservices.maplink2.com.br")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressFinderSoap {


    /**
     * Devolve uma lista contendo POI candidatos.
     * 
     * @param city
     * @param name
     * @param resultRange
     * @param token
     * @return
     *     returns br.com.maplink2.webservices.POIInfo
     */
    @WebMethod(action = "http://webservices.maplink2.com.br/findPOI")
    @WebResult(name = "findPOIResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "findPOI", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.FindPOI")
    @ResponseWrapper(localName = "findPOIResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.FindPOIResponse")
    public POIInfo findPOI(
        @WebParam(name = "name", targetNamespace = "http://webservices.maplink2.com.br")
        String name,
        @WebParam(name = "city", targetNamespace = "http://webservices.maplink2.com.br")
        City city,
        @WebParam(name = "resultRange", targetNamespace = "http://webservices.maplink2.com.br")
        ResultRange resultRange,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        String token);

    /**
     * Devolve uma lista contendo endereços candidatos.
     * 
     * @param address
     * @param ao
     * @param token
     * @return
     *     returns br.com.maplink2.webservices.AddressInfo
     */
    @WebMethod(action = "http://webservices.maplink2.com.br/findAddress")
    @WebResult(name = "findAddressResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "findAddress", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.FindAddress")
    @ResponseWrapper(localName = "findAddressResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.FindAddressResponse")
    public AddressInfo findAddress(
        @WebParam(name = "address", targetNamespace = "http://webservices.maplink2.com.br")
        Address address,
        @WebParam(name = "ao", targetNamespace = "http://webservices.maplink2.com.br")
        AddressOptions ao,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        String token);

    /**
     * Devolve o endereço do ponto informado.
     * 
     * @param point
     * @param tolerance
     * @param token
     * @return
     *     returns br.com.maplink2.webservices.AddressLocation
     */
    @WebMethod(action = "http://webservices.maplink2.com.br/getAddress")
    @WebResult(name = "getAddressResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getAddress", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetAddress")
    @ResponseWrapper(localName = "getAddressResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetAddressResponse")
    public AddressLocation getAddress(
        @WebParam(name = "point", targetNamespace = "http://webservices.maplink2.com.br")
        Point point,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        String token,
        @WebParam(name = "tolerance", targetNamespace = "http://webservices.maplink2.com.br")
        double tolerance);

    /**
     * Devolve a coordenada do endereço informado.
     * 
     * @param address
     * @param token
     * @return
     *     returns br.com.maplink2.webservices.Point
     */
    @WebMethod(action = "http://webservices.maplink2.com.br/getXY")
    @WebResult(name = "getXYResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getXY", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetXY")
    @ResponseWrapper(localName = "getXYResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetXYResponse")
    public Point getXY(
        @WebParam(name = "address", targetNamespace = "http://webservices.maplink2.com.br")
        Address address,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        String token);

    /**
     * Devolve a a coordenada do ponto informado e a URL do mapa.
     * 
     * @param mo
     * @param address
     * @param radius
     * @param token
     * @return
     *     returns br.com.maplink2.webservices.MapInfo
     */
    @WebMethod(action = "http://webservices.maplink2.com.br/getXYRadiusWithMap")
    @WebResult(name = "getXYRadiusWithMapResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "getXYRadiusWithMap", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetXYRadiusWithMap")
    @ResponseWrapper(localName = "getXYRadiusWithMapResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetXYRadiusWithMapResponse")
    public MapInfo getXYRadiusWithMap(
        @WebParam(name = "address", targetNamespace = "http://webservices.maplink2.com.br")
        Address address,
        @WebParam(name = "mo", targetNamespace = "http://webservices.maplink2.com.br")
        MapOptions mo,
        @WebParam(name = "radius", targetNamespace = "http://webservices.maplink2.com.br")
        int radius,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        String token);

    /**
     * Devolve uma lista contendo dados da cidade informada.
     * 
     * @param cidade
     * @param ao
     * @param token
     * @return
     *     returns br.com.maplink2.webservices.CityLocationInfo
     */
    @WebMethod(action = "http://webservices.maplink2.com.br/findCity")
    @WebResult(name = "findCityResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "findCity", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.FindCity")
    @ResponseWrapper(localName = "findCityResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.FindCityResponse")
    public CityLocationInfo findCity(
        @WebParam(name = "cidade", targetNamespace = "http://webservices.maplink2.com.br")
        City cidade,
        @WebParam(name = "ao", targetNamespace = "http://webservices.maplink2.com.br")
        AddressOptions ao,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        String token);

    /**
     * Devolve a coordenada de um cruzamento
     * 
     * @param cidade
     * @param secondStreet
     * @param firstStreet
     * @param token
     * @return
     *     returns br.com.maplink2.webservices.ArrayOfCrossStreetLocation
     */
    @WebMethod(operationName = "GetCrossStreetXY", action = "http://webservices.maplink2.com.br/GetCrossStreetXY")
    @WebResult(name = "GetCrossStreetXYResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "GetCrossStreetXY", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetCrossStreetXY")
    @ResponseWrapper(localName = "GetCrossStreetXYResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetCrossStreetXYResponse")
    public ArrayOfCrossStreetLocation getCrossStreetXY(
        @WebParam(name = "cidade", targetNamespace = "http://webservices.maplink2.com.br")
        City cidade,
        @WebParam(name = "firstStreet", targetNamespace = "http://webservices.maplink2.com.br")
        String firstStreet,
        @WebParam(name = "secondStreet", targetNamespace = "http://webservices.maplink2.com.br")
        String secondStreet,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        String token);

    /**
     * Devolve os cruzamentos de uma coordenada
     * 
     * @param point
     * @param token
     * @return
     *     returns br.com.maplink2.webservices.ArrayOfAddressLocation
     */
    @WebMethod(operationName = "GetCrossStreetAddress", action = "http://webservices.maplink2.com.br/GetCrossStreetAddress")
    @WebResult(name = "GetCrossStreetAddressResult", targetNamespace = "http://webservices.maplink2.com.br")
    @RequestWrapper(localName = "GetCrossStreetAddress", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetCrossStreetAddress")
    @ResponseWrapper(localName = "GetCrossStreetAddressResponse", targetNamespace = "http://webservices.maplink2.com.br", className = "br.com.maplink2.webservices.GetCrossStreetAddressResponse")
    public ArrayOfAddressLocation getCrossStreetAddress(
        @WebParam(name = "point", targetNamespace = "http://webservices.maplink2.com.br")
        Point point,
        @WebParam(name = "token", targetNamespace = "http://webservices.maplink2.com.br")
        String token);

}
