
package br.com.maplink2.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddressFinder", targetNamespace = "http://webservices.maplink2.com.br", wsdlLocation = "http://localhost.maplink.com/addressFinder?wsdl")
public class AddressFinder
    extends Service
{

    private final static URL ADDRESSFINDER_WSDL_LOCATION;
    private final static WebServiceException ADDRESSFINDER_EXCEPTION;
    private final static QName ADDRESSFINDER_QNAME = new QName("http://webservices.maplink2.com.br", "AddressFinder");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost.maplink.com/addressFinder?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDRESSFINDER_WSDL_LOCATION = url;
        ADDRESSFINDER_EXCEPTION = e;
    }

    public AddressFinder() {
        super(__getWsdlLocation(), ADDRESSFINDER_QNAME);
    }

    /**
     * 
     * @return
     *     returns AddressFinderSoap
     */
    @WebEndpoint(name = "AddressFinderSoap")
    public AddressFinderSoap getAddressFinderSoap() {
        return super.getPort(new QName("http://webservices.maplink2.com.br", "AddressFinderSoap"), AddressFinderSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressFinderSoap
     */
    @WebEndpoint(name = "AddressFinderSoap")
    public AddressFinderSoap getAddressFinderSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.maplink2.com.br", "AddressFinderSoap"), AddressFinderSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDRESSFINDER_EXCEPTION!= null) {
            throw ADDRESSFINDER_EXCEPTION;
        }
        return ADDRESSFINDER_WSDL_LOCATION;
    }

}
